secret:
  jwt:
    key: ENC(pJyY2N352qhAcC5/6lWtro6d+For9hI/cbua7SMbP121jsewpaMHYz4z22zwo+w4blILvGWLuSsVh7fb8bbx4Gi3YAwoCv3rXOuXQikAt4o=)
    signature: ENC(6FZdAAIi2htp3OwQzOqnmK5tbtNLVvGO)

  kakao:
    client-id: ENC(egCrmTnMY/kGZNYJwP7O+dHISas8fVWFmO4bF9M6zkDHi02moIaexhENauQDBduD)
    client-secret: ENC(Eo3sbkxTa8NAnpb3OOhhhKMeu+O9KBpsIQsDL57wiISyA6T+wqfaaeJglbyurx3h)
    logout-redirect-url: ENC(cQFggzXPK6NQs7Aj/K1V5zlkGvJcXLtvNPsWBx7KiQ2DFxeoMi2+w41q9go7gIoHQ1pDFM+l++g=)
