secret:
  jwt:
    key: ENC(pJyY2N352qhAcC5/6lWtro6d+For9hI/cbua7SMbP121jsewpaMHYz4z22zwo+w4blILvGWLuSsVh7fb8bbx4Gi3YAwoCv3rXOuXQikAt4o=)

  kakao:
    client-id: ENC(KMVPUvKK/JMme0fEig2wKRfjWBiYfWS/liyB2Q0La3y7wAkI6JhjaoXnX2DdxX9J)
    redirect-uri: ENC(EfJXHmvrYlbLQ0KMnXQf7+wOl9rcSolSSPxN0QqTLH+OerjpatjCJUSiVYlZfUHUnfXZEewlmd0=)
    client-secret: ENC(tmptmptmp)
