spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(fC2kedwqs/VVMGmAiwgI3qNmnoYmqWAuXGeoMY66DomELjOLJRT4fDGNLt5t7FQAuHJhzTiygKThjtqd2JBFjQzy9mNmwDUT0G+LUNZv2XM0U4ar8JPFdA==)
    username: ENC(pj2OQDc7CO49Fd/+rLWsjg==)
    password: ENC(SSttdjWt+qKzOLgwTL2cgUtEce9wbS8I)

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(tGwdWhKp3JANKDooNLD7c4uxrljB6JUuL0RGqUTIwf8INRmmQEAUbMMZY4XpcinE)
    username: ENC(sU5cFR/NcS3lcWR+BE7tJw==)
    password: ENC(E0BPQSOtdRe3yrRS/F2AZ9iCkzZfXAT8)
