name: Auto assgin

on:
  pull_request:
  issues:
    types: [opened, labeled, unlabeled]

env:
  REVIEWERS: 2jie0516, kys0411, Hejow

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
          reviewers: ${{ env.REVIEWERS }}
